config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :equipments
	root 'equipments#index'
	# 'equipments' => 'equipments#index'
	post 'equiments' => 'equiments#create'
	get 'equiments/:id' => 'equiments#show'
	get 'equipments/:id/edit' => 'equipments#edit'
	patch 'equipments/:id' => 'equipments#update'
	delete 'equipments/:id' => 'equipments#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
	belongs_to :user
	validates :name, :e_number, :m_number, :make, :lab_location, :date_of_installation, :current_status,
		presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :Equipment
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
	def index
		if user_signed_in?
			@equipments = Equipment.where(:user_id => current_user.id)
		end
		if user_signed_in? && current_user.admin?
			@equipments = Equipment.all
		end
	end

	def new
		@equipment = current_user.Equipment.build

	end

	def create
		equipment = current_user.Equipment.build(equipment_params)
		if equipment.save
			redirect_to "/equipments"
		else
			flash[:errors]=equipment.errors.full_messages
			redirect_to "/equipments/new"
		end
	end

	def show
		@equipment = Equipment.find(params[:id])
	end

	def edit
		@equipment = Equipment.find(params[:id])
	end

	def update
		equipment = Equipment.find(params[:id])
		if current_user.admin?
			if equipment.approved == false
			    equipment.update_attribute(:approved, 'True')
				redirect_to "/equipments"
			else
				equipment.update_attribute(:approved, 'false')
				redirect_to "/equipments"
			end
		else
		if equipment.update(equipment_params)
			redirect_to "/equipments"
		else
			flash[:errors]=equipment.errors.full_messages
			redirect_to "/equipments/<%= @equipment.id %>/edit"
		end
		end
	end


	def destroy
		equipment = Equipment.find(params[:id])
		equipment.destroy
		redirect_to "/equipments"
	end

	
		
	


private
	def equipment_params
		params.require(:equipment).permit(:name,:e_number,:m_number,:make,:lab_location,:date_of_installation,:current_status)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/views/equipments/edit.html.erb
<% content_for(:title, "Edit Equipment") %>

<h1>Edit <%= @equipment.name %> Details</h1>

<% if flash[:errors] %>
	<% flash[:errors].each do |e| %>
		<p><%= e %></p>
	<% end %>
<% end %>

<form action="/equipments/<%= @equipment.id %>" method="post">
	<input type="hidden" name="_method" value="patch">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<p>
		<label>Name:</label>
		<input type="text" name="equipment[name]" value="<%= @equipment.name %>">
	</p>
	<p>
		<label>Number:</label>
		<input type="number" name="equipment[e_number]" value="<%= @equipment.e_number %>">
	</p>
	<p>
		<label>Model Number:</label>
		<input type="text" name="equipment[m_number]" value="<%= @equipment.m_number %>">
	</p>
	<p>
		<label>Make:</label>
		<input type="number" name="equipment[make]" value="<%= @equipment.make %>">
	</p>
	<p>
		<label>Lab location:</label>
		<input type="text" name="equipment[lab_location]" value="<%= @equipment.lab_location %>">
	</p>
	<p>
		<label>Installation Date:</label>
		<input type="Date" name="equipment[date_of_installation]" value="<%= @equipment.date_of_installation %>">
	</p>
	<p>
		<label>Status:</label>
		<input type="text" name="equipment[current_status]" value="<%= @equipment.current_status %>">
	</p>
	<input type="submit" value="UPDATE">	
</form>
<%= link_to "Go back", equipments_path %>

app/views/equipments/index.html.erb
<% content_for(:title, "ITS") %>

<% if user_signed_in? %>

	<h1>Listing <%= pluralize(@equipments.length, "equipment", plural: "equipments") %></h1>
	<%= link_to "Add Equipment", new_equipment_path, class: "btn btn-primary"%>

	<table class="table">
		<thead>
			<td>Equipment_Name</td>
			<td>Equipment_Number</td>
			<td>Actions</td>
		</thead>

		<tbody>
			<% @equipments.each do |equipment| %>
			<tr>
				<td><%= equipment.name %></td>
				<td><%= equipment.e_number %></td>
				<td>
					<a href="equipments/<%= equipment.id %>">See Details</a> |
					<a href="equipments/<%= equipment.id %>/edit">Edit Details</a> |
					<% if current_user && current_user.admin? %>
						<a href="equipments/<%= equipment.id %>" data-method='Delete' data-confirm='Are you sure?'>Remove Equipment</a> |
						<% if equipment.approved==false %>
							<a href="equipments/<%= equipment.id %>" data-method='Patch' data-confirm='Click OK to Approve?' class= "btn btn-success">Approve</a>
							<% else %>
							<a href="equipments/<%= equipment.id %>" data-method='Patch' data-confirm='Click OK to Dispprove?' class= "btn btn-danger">Disapprove</a>
						<% end %>
					<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<%= render 'layouts/static_landing_page' %>
<% end %>

app/views/equipments/new.html.erb
<% content_for(:title, "Add Equipment") %>

<h1>Add new Equipment</h1>

<% if flash[:errors] %>
	<% flash[:errors].each do |e| %>
		<p><%= e %></p>
	<% end %>
<% end %>


<form action="/equipments" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<p>
		<label>Name:</label>
		<input type="text" name="equipment[name]">
	</p>
	<p>
		<label>Number:</label>
		<input type="number" name="equipment[e_number]">
	</p>
	<p>
		<label>Model Number:</label>
		<input type="text" name="equipment[m_number]">
	</p>
	<p>
		<label>Make:</label>
		<input type="number" name="equipment[make]">
	</p>
	<p>
		<label>Lab location:</label>
		<input type="text" name="equipment[lab_location]">
	</p>
	<p>
		<label>Installation Date:</label>
		<input type="Date" name="equipment[date_of_installation]">
	</p>
	<p>
		<label>Status:</label>
		<input type="text" name="equipment[current_status]">
	</p>
	<input type="submit" value="ADD">	
</form>

<%= link_to "Go back", equipments_path %>

app/views/equipments/show.html.erb
<% content_for(:title, "Equipment Info") %>

<h1>This page contains details of <%= @equipment.name %></h1>
	<p>
		<label>Name:</label>
		<%= @equipment.name %>
	</p>
	<p>
		<label>Number:</label>
		<%= @equipment.e_number %>
	</p>
	<p>
		<label>Model Number:</label>
		<%= @equipment.m_number %>
	</p>
	<p>
		<label>Make:</label>
		<%= @equipment.make %>
	</p>
	<p>
		<label>Lab location:</label>
		<%= @equipment.lab_location %>
	</p>
	<p>
		<label>Installation Date:</label>
		<%= @equipment.date_of_installation %>
	</p>
	<p>
		<label>Status:</label>
		<%= @equipment.current_status %>
	</p>

<%= link_to "Go back", equipments_path %>

app/views/layouts/_static_landing_page.html.erb
<div class="jumbotron">
	<h1>Welcome to Inventory Tracking System</h1>
	<p>CSED Department</p>
	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
	<%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Inventory', equipments_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          
          <% if current_user.present? %>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %> 
        </ul>
      </div> 
      
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>